name: msr605x-utility
version: '1.0.0'
summary: MSR605X Magnetic Stripe Card Reader/Writer Utility
description: |
  A native GTK4 application for Ubuntu to read, write, and manage
  magnetic stripe cards using the MSR605X device.

  Features:
  - Read/Write/Erase magnetic stripe cards
  - Automatic device detection and connection
  - Support for ISO and Raw data formats
  - Hi-Co and Lo-Co coercivity configuration
  - Save/Load card data in JSON/CSV format
  - Modern GTK4/libadwaita interface

  Supported Hardware:
  - MSR605X USB Magnetic Stripe Card Reader/Writer

  Note: After installation, connect the raw-usb interface with:
  sudo snap connect msr605x-utility:raw-usb

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: [amd64]
    build-for: [amd64]

apps:
  msr605x-utility:
    command: usr/bin/python3 -m src.main
    desktop: usr/share/applications/com.github.msr605x.desktop
    extensions: [gnome]
    plugs:
      - home
      - raw-usb
      - hardware-observe
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.10/site-packages

plugs:
  raw-usb:
  hardware-observe:

parts:
  msr605x-utility:
    plugin: python
    source: .
    build-packages:
      - python3-dev
      - libhidapi-dev
    python-packages:
      - hidapi
    stage-packages:
      - libhidapi-hidraw0
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-4.0
      - gir1.2-adw-1
      - libgtk-4-1
      - libadwaita-1-0

  desktop-files:
    plugin: dump
    source: data/
    organize:
      com.github.msr605x.desktop: usr/share/applications/com.github.msr605x.desktop
      com.github.msr605x.svg: usr/share/icons/hicolor/scalable/apps/com.github.msr605x.svg
      style.css: usr/share/msr605x/style.css
