name: msr605x-utility
version: '1.0.0'
summary: MSR605X Magnetic Stripe Card Reader/Writer Utility
description: |
  A native GTK4 application for Ubuntu to read, write, and manage
  magnetic stripe cards using the MSR605X device.

  **Features:**
  - Read/Write/Erase magnetic stripe cards
  - Support for ISO, AAMVA, and Raw data formats
  - Hi-Co and Lo-Co coercivity configuration
  - BPI and BPC settings per track
  - Save/Load card data in JSON/CSV format
  - Modern GTK4/libadwaita interface
  - Device diagnostic tests

  **Supported Hardware:**
  - MSR605X USB Magnetic Stripe Card Reader/Writer
  - Compatible MSR605/MSR606 devices

  **Note:** After installation, you may need to connect the raw-usb interface:
  `sudo snap connect msr605x-utility:raw-usb`

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64

apps:
  msr605x-utility:
    command: usr/bin/msr605x-gui
    desktop: usr/share/applications/com.github.msr605x.desktop
    extensions: [gnome]
    plugs:
      - home
      - raw-usb
      - hardware-observe
    environment:
      GTK_USE_PORTAL: '1'

layout:
  /usr/share/msr605x:
    bind: $SNAP/usr/share/msr605x

parts:
  msr605x-utility:
    plugin: python
    source: .
    python-packages:
      - hidapi
    stage-packages:
      - libhidapi-hidraw0
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-4.0
      - gir1.2-adw-1
    override-build: |
      craftctl default
      # Install desktop file
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      cp data/com.github.msr605x.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/
      # Install icon
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/scalable/apps
      cp data/com.github.msr605x.svg $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/scalable/apps/
      # Install CSS
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/msr605x
      cp data/style.css $SNAPCRAFT_PART_INSTALL/usr/share/msr605x/
      # Create launcher script
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      cat > $SNAPCRAFT_PART_INSTALL/usr/bin/msr605x-gui << 'EOF'
      #!/bin/bash
      exec python3 -m src.main "$@"
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/msr605x-gui

plugs:
  raw-usb:
    interface: raw-usb
  hardware-observe:
    interface: hardware-observe
